name: bloc_integration
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_modular: ^3.3.1
  mocktail: ^0.1.4
  rxdart: ^0.27.1
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/animations/lotties/